port = 1928

[language]
	server = "english"
	client = "english"

[ratelimit]
	cubes = 24
	chat = 8

[defaults.world]
	size = [ 64, 64, 64 ]
	palette = [	'FFFFFF', 'AAAAAA', '777777', '484848', '000000',
				'991609', 'F3280C', 'FF5610', 'FF832A', 'FFB885',
				'936100', 'E29705', 'FFD223', 'FFF280', '47561E',
				'71892B', '94BE1A', 'DCFF77', '124B36', '0F8158',
				'03C07C', '90FFCA', '024851', '0D7A89', '01A6BD',
				'34E7FF', '013462', '0D569A', '066ECE', '4CA9FF',
				'181691', '2A25F5', '4E55FF', '9DB8FF', '58196B',
				'AC01E0', 'C82EF7', 'DC91FF', '650036', 'B0114B',
				'EA3477', 'FF95BC', '62071D', '9B0834', 'CB003D',
				'FF7384', '49230A', '814A17', 'D17A2B', 'FF9D59' ]

[dsbridge]
	enabled = false
	channelId = "the channel where messages will be bridged"
	webhookUrl = "sends the messages from game to discord"
	botToken = "sends the messages from discord to game"